reclaim_api_key = "RECLAIM_API_KEY"
notion_api_key = "NOTION_API_KEY"

[[databases]]
database_id = "DATABASE_01"
sync_priority = "Notion"

[[databases]]
database_id = "DATABASE_02"
sync_priority = "Reclaim"
