reclaim_api_key = "RECLAIM_API_KEY"
notion_api_key = "NOTION_API_KEY"

[[databases]]
notion_database_id = "DATABASE_01"
sync_priority = "NOTION"

[[databases]]
notion_database_id = "DATABASE_02"
sync_priority = "RECLAIM"
